### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by leotongxue** [pangkun248/Faster-RCNN-PyTorch#1]
请问您数据集是怎么建立的

**Comment by pangkun248** [comment]
> 请问您数据集是怎么建立的

已上传数据集范例.如果有其他不清楚的欢迎留言

**Comment by xu911** [comment]
您好，请问您代码的运行环境是什么，支持torch1.2或以上版本吗？谢谢.

**Comment by pangkun248** [comment]
> 您好，请问您代码的运行环境是什么，支持torch1.2或以上版本吗？谢谢.

win10 支持
