### ISSUE TITLE
权重使用

### ISSUE THREAD

**Issue by leotongxue** [pangkun248/Faster-RCNN-PyTorch#2]
权重有下载链接吗 应该怎么修文件 才可以运行

**Comment by pangkun248** [comment]
https://github.com/pangkun248/Faster-RCNN-PyTorch/blob/165a071b64bf98420e2774b020a83ce78449e802/model.py#L14

**Comment by leotongxue** [comment]
直接直接train.py下面这两行就可以吧
    if opt.load_path:
        model.load(opt.load_path)
